DOMAIN = "sleep_as_ha"
DEVICE_MACRO: str = "%%%device%%%"

DEFAULT_NAME = "SleepAsHA"
DEFAULT_TOPIC_TEMPLATE = "SleepAsHA/%s" % DEVICE_MACRO
DEFAULT_ALARM_TOPIC_TEMPLATE = "%s/alarms" % DEFAULT_TOPIC_TEMPLATE
DEFAULT_QOS = 0
DEFAULT_ALARM_LABEL = ""

CONF_ALARMS = "alarms"
CONF_ALARM_TIME_FMT = "%I:%M %p"
CONF_ALARM_DATE_FMT = "%a, %b %d, %Y"
CONF_ALARM_LABEL = "label"
CONF_ALARM_TIME = "time"
CONF_ALARM_DATE = "date"
CONF_ALARM_REPEAT = "repeat"
CONF_ALARM_ADD_ANOTHER = "add_another"
